### ISSUE TITLE
Section nav icons for surveys

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#450]
We need 296x225px icons for the section nav menu in the Survey section, for the following sub-sections:

* Surveys
* Survey submissions

Assigning to myself and @jensborje. Lets discuss what to use and who produces them.

**Comment by jensborje** [comment]
Here's my suggested solution.

For surveys, we focus not on the list but of the survey items. Using a simplified list of checkboxes, we differentiate the list from other kinds of lists in other sections. Having one of them checked, we enhance the interpretation of being able to be in different states - like checkboxes act. Being in different lengths, we tell that their content differ from each other.

For submissions, in order to differentiate from the survey base pane, but still have it's presence in context, we focus on the _incoming_ part of the page. A inbox and a downwards arrow would be sufficient for this as it's a reoccurring pattern on other sites and applications.

![screen shot 2017-02-25 at 11 15 30](https://cloud.githubusercontent.com/assets/1271517/23330386/01e8fa94-fb4d-11e6-9e62-e26cedde7c2b.png)

**Comment by richardolsson** [comment]
Looking good!
