### ISSUE TITLE
Horizontal scrolling in import

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#516]
At least one user has testified that they did not understand that you can scroll horizontally in the import interface. This is an issue especially when the table is long, because the scroll bar at the bottom is off-screen, and if the interface is slow (as is the case with large files, see #515) it's even less apparent that you can scroll.

It would be good with some other option for navigating left/right. Perhaps some sort of button to step column by column?

**Comment by jensborje** [comment]
**Goals**
- Communicate that there are more columns offscreen.
- Intuitive understanding of navigation.

**Possible controllers**
- Horizontal scrollbar
- Stepping buttons
- Scroll on hover to the sides

Scrollbars are great for give a visual sense of onscreen content in relation to off screen. It is also a common learned controller easy to use. Perhaps a custom horizontal scrollbar could be useful?

If to use stepping buttons, one must make sure that the user is able to understand they control the columns, or rather the visible workspace. This could be solved by placement to the far left and right of the on screen columns, but also depending on how they look. A standard button with icon is easy to interpret as a controller, but what they control might not always be so obvious. 
An alternative could be to use areas in context of the columns with a stepping icon inside of them. This could however take up space otherwise to be used by the columns, especially the one to the far right that is partially off screen giving sense of more content.
Stepping one-by-one could lead to a slow workflow if to be the only method.

Alternatively - or in combination - we could use areas to the far left and right that scrolls when hovering on them. Here we also would need the visual equivalent of a scrollbar for orientation.

Perhaps some mashup of these is the solution?

**Comment by richardolsson** [comment]
Fixed by #519.
