### ISSUE TITLE
Responsive/mobile layout

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#898]
Finalize, improve and release the mobile layout. Work on this started early in the process of developing Organize, but was never finished.

**Comment by jensborje** [comment]
## UX analysis ##
Note: Not all in the following is to be considered within the scope of this issue.

### What differs from desktop usage? ###
Desktop usage is in a workspace, a controlled and (hopefully) focused environment. The tool has the users primary attention. This makes is suitable for planning and analyzing.

Mobile usage is in a more uncontrolled and dynamic environment. It can be on a bus, on the street or in a sofa next to the workspace. Often, dialogs with others are close at hand. The attention of the user could therefore be potentially on another person primarily or shared with other needs such as orientation. This gives the mobile usage a high potential in situations where a user needs status reports as support to a conversation, or to carry through the result of a conversation or a outer situation immediately, such as adding a person to a task you agreed to.

Since the environment is potentially changing by outer circumstances, usage duration tends to be short. This makes mobile usage not suitable for activities such as planning or analyzing.
The potentially secondary attention, and the limited usage duration, highlights the needs for accessibility for tasks that is often used in situations related to the usage environment. This increases the need of a task driven rather than a conceptual driven navigation which is more often used when designing for desktop usage.

These different needs between device usage clashes however with another need - to build an understanding of the tools features and recognition across the platform. This usually results in attempts to keep the experiences as similar as possible. A potential reason for this could be that it also aligns with business needs such as marketing. A compromise often seen is device specific shortcuts.

### Not yet investigated ###
- Screen limitations VS handheld potential in terms of intuitive navigation

### Potential needs within the mobile usage scope ###

* Ongoing projects
  * Monitor progress
  * Manage participants


* Mobilize
  * Actions
    * Edit, add and remove actions
    * Manage participants
    * Send reminders


* Member management
  * Look up members
    * Smart searches
    * Update member info
  * Manage groups
    * Edit, add and remove groups
    * Update group members
  * Review survey submissions

**Comment by jensborje** [comment]
### Pages relevant for mobile usage ###

**/people**
/list
~~/import~~
/groups
/manage

**/campaign**
/actions
~~/distribution~~
~~/playback~~
/campaigns

**/dialog**
/assignments
/calls

**~~/maps~~**
~~/overview~~
~~/locations~~

**~~/survey~~**  *
~~/surveys~~
~~/submissions~~

**/canvass**
/assignments
~~/routes~~
_/visits_

**~~/settings~~**
~~/officials~~

\* Following the reasoning in the UX analysis, survey should probably partly be included in the scope of mobile usage, not as a separate section but as part of the person pane. This would however require features not currently existing atm.

**Comment by jensborje** [comment]
## Tasks relevant for mobile usage ##
As a step towards finding the implications of the UX analysis, the following reviews the currently available features in relation to the needs for the mobile usage scope to determine what is relevant.

### Campaign ###
**Planning**
~~Campaign overview planner~~

**Analysing**
~~Distribution~~
~~Playback~~

**Importing/Exporting**
~~Import actions~~
~~Bulk export actions~~

**Manage Campaigns**
Review campaigns
Edit and delete campaign
Create new campaign

**Manage actions**
List planned actions
Sign-up status 
View action details
Edit and delete action
Create new action
Manage participants
Send reminders

As an example, since we don't build for planning but for maintaining, we remove the calendar looking "campaign overview planner" but keep the corresponding Action list.

**Comment by richardolsson** [comment]
Fixed by #956
