### ISSUE TITLE
Edit query pane closes when adding Linked smart search query to call assignment

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#995]
Edit query pane closes down unexpectedly when trying to edit call assignment target, adding a linked smart search query.

Steps to reproduce:
When editing targets for call assignment, add filter and select Linked smart search query.

**Comment by richardolsson** [comment]
The reason seems to be that a new list is created on this line, instead of just adding the newly retrieved queries.

https://github.com/zetkin/organize.zetk.in/blob/c2b79c836ad74b334730c3e6cf609c4e275aad79/src/store/queries.js#L22

The flow as I've found it:

1. Opening the `CallAssignmentPane` results in the assignment and it's queries being loaded and stored in the `queries` section of the store
2. Mounting the `SubQueryFilter` component initiates a retrieval of _all_ call assignments and queries
3. When the queries finish loading, the list in the `queries` store is replaced with a new list, which does not contain the call assignments (yet)
4. When `EditQueryPane` receives the new store, without any call assignment queries, `componentWillReceiveProps()` closes the pane

Ideas for solving:
* On the line above, use `updateOrAddListItems()` (plural) instead, and/or
* Don't `closePane()` in `EditQueryPane` if query is empty, just render nothing.
